version: "3.9"
services:
 frontend:
  container_name: frontend 
  build: ./frontend
  volumes:
    - ./frontend:/app
    - /app/node_modules
  ports: 
    - "3000:5173"
 backend:
  container_name: backend
  build: ./backend
  volumes: 
    - ./backend:/backend
    - /app/node_modules
  ports:
     - "8080:8080"
